/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compare */
        post: operations["compare_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Run */
        post: operations["create_run_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply Event */
        post: operations["apply_event_runs__run_id__events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/flows/{flow_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Flow Decision */
        get: operations["flow_decision_runs__run_id__flows__flow_id__decision_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Run */
        post: operations["reset_run_runs__run_id__reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scenarios */
        get: operations["list_scenarios_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Allocation */
        Allocation: {
            /** Arc Load */
            arc_load: {
                [key: string]: number;
            };
            /** Results */
            results: {
                [key: string]: components["schemas"]["FlowResult"];
            };
        };
        /** Attempt */
        Attempt: {
            /** Arcs */
            arcs: string[];
            /** Bottleneck */
            bottleneck: number;
            /** Cost */
            cost: number;
            /** Iter */
            iter: number;
            /** Latency */
            latency: number;
            /** Pushed */
            pushed: number;
        };
        /** CompareRequest */
        CompareRequest: {
            config?: components["schemas"]["PolicyConfig"] | null;
            /** Policies */
            policies: string[];
            scenario?: components["schemas"]["Scenario"] | null;
            /** Scenario Id */
            scenario_id?: string | null;
        };
        /**
         * CompareResponse
         * @description Self-contained, so a saved `compare --out` file renders with no server.
         */
        CompareResponse: {
            /** Flows */
            flows: components["schemas"]["Flow"][];
            scenario: components["schemas"]["Scenario"];
            /** Snapshots */
            snapshots: {
                [key: string]: components["schemas"]["Snapshot"][];
            };
            /** Table */
            table: components["schemas"]["CompareRow"][];
            topology: components["schemas"]["Topology"];
        };
        /** CompareRow */
        CompareRow: {
            metrics: components["schemas"]["Metrics"];
            /** Policy */
            policy: string;
        };
        /** CutArc */
        CutArc: {
            /** Arc */
            arc: string;
            /** Load By Class */
            load_by_class: {
                [key: string]: number;
            };
            /**
             * State
             * @enum {string}
             */
            state: "saturated" | "down";
        };
        /** DecisionRecord */
        DecisionRecord: {
            /** Attempts */
            attempts: components["schemas"]["Attempt"][];
            /**
             * Cause
             * @enum {string}
             */
            cause: "NONE" | "DISCONNECTED" | "INSUFFICIENT_CAPACITY" | "PATH_LIMIT" | "OVERLOAD_LOSS";
            /** Cls */
            cls: number;
            /** Cut */
            cut: components["schemas"]["CutArc"][];
            /** Delivered */
            delivered: number;
            /** Demand */
            demand: number;
            /** Explanation */
            explanation: string;
            /** Failed Links */
            failed_links: string[];
            /** Flow Id */
            flow_id: string;
            /** Greedy Gap */
            greedy_gap: number | null;
            /** Maxflow Bound */
            maxflow_bound: number | null;
            /** Previous */
            previous: components["schemas"]["PathAlloc"][];
            /** Reference Path */
            reference_path: string[];
            /** Reference Status */
            reference_status: string;
            /** Step */
            step: number;
            /** Unserved */
            unserved: number;
        };
        /** Event */
        Event: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "fail" | "recover";
            /**
             * Links
             * @default []
             */
            links: string[];
            /** Node */
            node?: string | null;
            /** Step */
            step: number;
        };
        /**
         * EventRequest
         * @description The server assigns the step, so a stale client cannot send one.
         */
        EventRequest: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "fail" | "recover";
            /**
             * Links
             * @default []
             */
            links: string[];
            /** Node */
            node?: string | null;
        };
        /** Flow */
        Flow: {
            /** Cls */
            cls: number;
            /** Dst */
            dst: string;
            /** Id */
            id: string;
            /** Rate */
            rate: number;
            /**
             * Service
             * @default
             */
            service: string;
            /** Src */
            src: string;
        };
        /** FlowResult */
        FlowResult: {
            /**
             * Cause
             * @enum {string}
             */
            cause: "NONE" | "DISCONNECTED" | "INSUFFICIENT_CAPACITY" | "PATH_LIMIT" | "OVERLOAD_LOSS";
            /** Delivered */
            delivered: number;
            /** Flow Id */
            flow_id: string;
            /** Paths */
            paths: components["schemas"]["PathAlloc"][];
            /** Unserved */
            unserved: number;
        };
        /** GeneratedTopologySpec */
        GeneratedTopologySpec: {
            /** Buildings */
            buildings: number;
            /** Generator */
            generator: string;
            /** Redundancy */
            redundancy: number;
            /** Seed */
            seed: number;
        };
        /** GeneratedTrafficSpec */
        GeneratedTrafficSpec: {
            /** Class Mix */
            class_mix: {
                [key: string]: number;
            };
            /** Generator */
            generator: string;
            /** Load Factor */
            load_factor: number;
            /** N Flows */
            n_flows: number;
            /** Seed */
            seed: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Link */
        Link: {
            /** Capacity */
            capacity: number;
            /** Id */
            id: string;
            /** Latency */
            latency: number;
            /**
             * Status
             * @enum {string}
             */
            status: "up" | "down";
            /** U */
            u: string;
            /** V */
            v: string;
        };
        /** Metrics */
        Metrics: {
            /** Arcs Above 90 */
            arcs_above_90: number;
            /** Churn Flows */
            churn_flows: number;
            /** Churn Rate */
            churn_rate: number;
            /** Compute Ms */
            compute_ms: number;
            /** Dr */
            dr: number;
            /** Dr By Class */
            dr_by_class: {
                [key: string]: number;
            };
            /** Dr Reach */
            dr_reach: number;
            /** Latency Stretch */
            latency_stretch: number;
            /** Link Util */
            link_util: {
                [key: string]: number;
            };
            /** Max Util */
            max_util: number;
            /** Mean Util */
            mean_util: number;
            /** Overload Excess */
            overload_excess: number;
            /** Overloaded Arcs */
            overloaded_arcs: number;
            /** P0 Greedy Gap */
            p0_greedy_gap: number;
            /** Recovery Ratio */
            recovery_ratio: number | null;
            /** Unserved By Cause */
            unserved_by_cause: {
                [key: string]: number;
            };
        };
        /** Node */
        Node: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
        };
        /** PathAlloc */
        PathAlloc: {
            /** Arcs */
            arcs: string[];
            /** Rate */
            rate: number;
        };
        /** PolicyConfig */
        PolicyConfig: {
            /**
             * Congestion Lambda
             * @default 0
             */
            congestion_lambda: number;
            /**
             * Max Paths
             * @default 3
             */
            max_paths: number;
            /**
             * Order
             * @default class_size_desc
             * @enum {string}
             */
            order: "arrival" | "class_size_desc" | "class_size_asc";
            /**
             * Util Cap
             * @default 1
             */
            util_cap: number;
        };
        /** RunRequest */
        RunRequest: {
            config?: components["schemas"]["PolicyConfig"] | null;
            /** Policy */
            policy: string;
            scenario?: components["schemas"]["Scenario"] | null;
            /** Scenario Id */
            scenario_id?: string | null;
        };
        /** RunResponse */
        RunResponse: {
            /** Flows */
            flows: components["schemas"]["Flow"][];
            /** Run Id */
            run_id: string;
            scenario: components["schemas"]["Scenario"];
            snapshot: components["schemas"]["Snapshot"];
            topology: components["schemas"]["Topology"];
        };
        /** Scenario */
        Scenario: {
            config: components["schemas"]["PolicyConfig"];
            /** Events */
            events: components["schemas"]["Event"][];
            /** Id */
            id: string;
            /** Seed */
            seed: number;
            /** Topology */
            topology: components["schemas"]["TemplateTopologySpec"] | components["schemas"]["GeneratedTopologySpec"];
            /** Traffic */
            traffic: components["schemas"]["Flow"][] | components["schemas"]["GeneratedTrafficSpec"];
        };
        /** ScenarioInfo */
        ScenarioInfo: {
            /** Description */
            description: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** Snapshot */
        Snapshot: {
            /** Affected Flows */
            affected_flows: string[];
            allocation: components["schemas"]["Allocation"];
            /** Decisions */
            decisions: components["schemas"]["DecisionRecord"][];
            /** Link State */
            link_state: {
                [key: string]: "up" | "down";
            };
            metrics: components["schemas"]["Metrics"];
            /** Step */
            step: number;
        };
        /** TemplateTopologySpec */
        TemplateTopologySpec: {
            /** Template */
            template: string;
        };
        /** Topology */
        Topology: {
            /** Links */
            links: components["schemas"]["Link"][];
            /** Nodes */
            nodes: components["schemas"]["Node"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    compare_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_event_runs__run_id__events_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    flow_decision_runs__run_id__flows__flow_id__decision_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                flow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_run_runs__run_id__reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scenarios_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioInfo"][];
                };
            };
        };
    };
}
